version: '3'
services:
  MathFinder:
    build:
      context: .
      dockerfile: Dockerfile
    image: jpatrick1/mathfinder
    hostname: mf
    volumes:
      - ./training:/.mathfinder/training
      - ./data/Groundtruth/WithoutLabels:/.mathfinder/groundtruth
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - USER=$USER
      - DISPLAY=$DISPLAY
      - LD_LIBRARY_PATH=/usr/local/lib
      - TESSDATA_PREFIX=/usr/local/share
      - SCROLLVIEW_PATH=/usr/local/share/scrollview
    working_dir: /.mathfinder/groundtruth/
    entrypoint: bash
